version: "3.3"

services:
  backend:
    env_file: "./api/.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "hacker-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "hacker-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: wachu
      MONGO_INITDB_ROOT_PASSWORD: wachu
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
