export enum ACTION_TYPES {
  FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST",
  FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE",
  FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS",
  DELETE_ONE_POST = "DELETE_ONE_POST",
}

export type Action =
  | { type: ACTION_TYPES.FETCH_POSTS_REQUEST }
  | { type: ACTION_TYPES.FETCH_POSTS_FAILURE; payload: string }
  | { type: ACTION_TYPES.FETCH_POSTS_SUCCESS; payload: any[] }
  | { type: ACTION_TYPES.DELETE_ONE_POST; payload: string };
