version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: wachu
      MONGO_INITDB_ROOT_PASSWORD: wachu
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
